Adding notebook to calculate and view thickness map
uncbiag/OAI_analysis_2 pull request #3
Opened 2022-01-27 01:35 UTC by PranjalSahu

2022-01-27 01:56 UTC, thewtex requested changes

2022-01-27 01:56 UTC, thewtex commented on notebooks/ComputeThicknessDemo.ipynb
> +        "segmentation = [sitk.ReadImage(file) for file in segmentation_file]\n",
[itk.imread(file) for file in segmentation_file]

2022-01-27 01:56 UTC, thewtex commented on notebooks/ComputeThicknessDemo.ipynb
> +        "FC_prob = np.swapaxes(sitk.GetArrayFromImage(segmentation[0]), 0, 2).astype(float)\n",
np.asarray(segmentation[0])

2022-01-27 19:20 UTC, HastingsGreer commented
The safest way to convert from indices to physical space is to use FC_prob_img.TransformIndexToPhysicalPoint( ... ) . This will handle all spacing, orientation, origin, etc.

2022-01-28 20:21 UTC, PranjalSahu commented
Vectorizing some calculation to speed it up.

2022-02-14 19:51 UTC, merged